# Generated by Django 6.0.5 on 2026-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('lenght', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='api.movie'),
        ),
    ]
