# Generated by Django 6.0.5 on 2026-05-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_user_watched_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
