# Generated by Django 6.0.5 on 2026-05-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lenght',
            new_name='length',
        ),
    ]
